# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
        - image: circleci/android:api-28-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/KotlinCryptoKtx

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx1536m

    steps:
      - checkout
      - run: ls
# Try to restore cache
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
# Download and cache dependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
# Save to the cache so next build is faster
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      # run tests!
      - run:
          name: Run Tests
          command: ./gradlew lint test